import Link from "next/link";
import { ArrowUpRight, Clock3 } from "lucide-react";
import { getPosts } from "@/lib/posts";
export const dynamic = "force-dynamic";
export default async function Home({searchParams}:{searchParams:Promise<{q?:string;topic?:string}>}) {
  const {q="",topic=""}=await searchParams; const posts=await getPosts(); const topics=[...new Set(posts.map(p=>p.topic))];
  const shown=posts.filter(p=>(!topic||p.topic===topic)&&(!q||`${p.title} ${p.excerpt}`.toLowerCase().includes(q.toLowerCase())));
  return <main><section className="intro"><p className="eyebrow">A personal journal on software architecture</p><h1>Understanding systems,<br/><em>one trade-off at a time.</em></h1><p className="lede">Practical essays about distributed systems, reliability, and the decisions that shape software over time.</p></section><section className="writing" id="writing"><div className="section-head"><h2>Latest writing</h2><form><input name="q" defaultValue={q} placeholder="Search essays…" aria-label="Search essays"/></form></div><div className="topics"><Link className={!topic?"active":""} href="/">All</Link>{topics.map(t=><Link key={t} className={topic===t?"active":""} href={`/?topic=${encodeURIComponent(t)}#writing`}>{t}</Link>)}</div><div className="post-list">{shown.map((p,i)=><article className={`${i===0?"featured ":""}${p.coverImage?"has-cover":""}`} key={p.slug}>{p.coverImage&&<Link className="card-cover" href={`/posts/${p.slug}`}><img src={p.coverImage} alt={p.coverAlt||""}/></Link>}<div><span className="topic">{p.topic}</span><h3><Link href={`/posts/${p.slug}`}>{p.title}</Link></h3><p>{p.excerpt}</p><div className="meta"><time>{new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(p.publishedAt))}</time><span><Clock3 size={13}/>{p.readingMinutes} min read</span></div></div><Link className="open" href={`/posts/${p.slug}`} aria-label={`Read ${p.title}`}><ArrowUpRight/></Link></article>)}{shown.length===0&&<p className="empty">No essays match that search.</p>}</div></section></main>;
}
