"use client";
import { ClipboardPaste, Eye, ImagePlus, Italic, Link as LinkIcon, List, LoaderCircle, Quote, Sparkles, Type, X } from "lucide-react";
import { useRef, useState } from "react";
import { publish } from "@/app/admin/actions";
import { Markdown } from "@/components/markdown";
import type { Post } from "@/lib/types";

type UploadResult={url:string;name:string};
async function upload(file:File):Promise<UploadResult>{const body=new FormData();body.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body});const result=await response.json();if(!response.ok)throw new Error(result.error||"Upload failed.");return result;}
function inlineMarkdown(node:Node):string{if(node.nodeType===Node.TEXT_NODE)return node.textContent||"";if(!(node instanceof HTMLElement))return "";const el=node as HTMLElement,tag=el.tagName.toLowerCase(),text=Array.from(el.childNodes).map(inlineMarkdown).join("");if(tag==="strong"||tag==="b")return `**${text}**`;if(tag==="em"||tag==="i")return `*${text}*`;if(tag==="code")return `\`${text}\``;if(tag==="a")return `[${text}](${el.getAttribute("href")||""})`;if(tag==="br")return "\n";if(tag==="img")return `![${el.getAttribute("alt")||"Article illustration"}](${el.getAttribute("src")||""})`;return text;}
function blockMarkdown(node:Node):string{if(node.nodeType===Node.TEXT_NODE)return node.textContent?.trim()||"";if(!(node instanceof HTMLElement))return "";const tag=node.tagName.toLowerCase();if(["div","section","article","main"].includes(tag))return Array.from(node.childNodes).map(blockMarkdown).filter(Boolean).join("\n\n");const text=inlineMarkdown(node).trim();if(tag==="h1"||tag==="h2")return `## ${text}`;if(tag==="h3"||tag==="h4")return `### ${text}`;if(tag==="blockquote")return text.split("\n").map(line=>`> ${line}`).join("\n");if(tag==="ul")return Array.from(node.children).map(li=>`- ${inlineMarkdown(li).trim()}`).join("\n");if(tag==="ol")return Array.from(node.children).map((li,i)=>`${i+1}. ${inlineMarkdown(li).trim()}`).join("\n");if(tag==="pre")return `\`\`\`\n${node.textContent?.trim()||""}\n\`\`\``;if(tag==="hr")return "---";return text;}
function richTextToMarkdown(html:string):string{const body=new DOMParser().parseFromString(html,"text/html").body;return Array.from(body.childNodes).map(blockMarkdown).filter(Boolean).join("\n\n");}
function cleanFormatting(value:string){return value.replace(/\r\n/g,"\n").replace(/[ \t]+$/gm,"").replace(/\n{3,}/g,"\n\n").replace(/^\s*[•·]\s+/gm,"- ").trim();}

export function ArticleEditor({post}:{post?:Post}){
  const articleRef=useRef<HTMLTextAreaElement>(null);const [content,setContent]=useState(post?.content||"");const [cover,setCover]=useState<UploadResult|null>(post?.coverImage?{url:post.coverImage,name:"Existing cover"}:null);const [coverAlt,setCoverAlt]=useState(post?.coverAlt||"");const [busy,setBusy]=useState<"cover"|"inline"|null>(null);const [error,setError]=useState("");const [preview,setPreview]=useState(false);
  function replaceSelection(before:string,after="",placeholder="text"){const area=articleRef.current;if(!area)return;const start=area.selectionStart,end=area.selectionEnd,selected=content.slice(start,end)||placeholder;setContent(content.slice(0,start)+before+selected+after+content.slice(end));requestAnimationFrame(()=>{area.focus();area.setSelectionRange(start+before.length,start+before.length+selected.length)});}
  function prefixLines(prefix:string){const area=articleRef.current;if(!area)return;const start=area.selectionStart,end=area.selectionEnd,selected=content.slice(start,end)||"Text";const replacement=selected.split("\n").map(line=>`${prefix}${line}`).join("\n");setContent(content.slice(0,start)+replacement+content.slice(end));requestAnimationFrame(()=>area.focus());}
  function pasteRichText(event:React.ClipboardEvent<HTMLTextAreaElement>){const html=event.clipboardData.getData("text/html");if(!html)return;event.preventDefault();const converted=richTextToMarkdown(html),area=articleRef.current,start=area?.selectionStart??content.length,end=area?.selectionEnd??start;setContent(content.slice(0,start)+converted+content.slice(end));}
  async function addCover(file?:File){if(!file)return;setBusy("cover");setError("");try{setCover(await upload(file));}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(null)}}
  async function addInline(file?:File){if(!file)return;setBusy("inline");setError("");try{const image=await upload(file),area=articleRef.current,at=area?.selectionStart??content.length,markdown=`\n\n![Article illustration](${image.url})\n\n`;setContent(content.slice(0,at)+markdown+content.slice(at));requestAnimationFrame(()=>{area?.focus();area?.setSelectionRange(at+markdown.length,at+markdown.length)});}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(null)}}
  return <form action={publish} className="editor">{post&&<input type="hidden" name="originalSlug" value={post.slug}/>} {error&&<p className="notice error" role="alert">{error}</p>}
    <label>Title<input name="title" required defaultValue={post?.title} placeholder="A precise, useful title"/></label><div className="two"><label>Topic<input name="topic" required defaultValue={post?.topic} placeholder="Distributed systems"/></label><label>Status<select name="status" defaultValue={post?.status||"draft"}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><label>Summary<textarea name="excerpt" required rows={3} defaultValue={post?.excerpt} placeholder="What will the reader understand?"/></label>
    <fieldset className="cover-field"><legend>Cover image <span>Optional</span></legend>{cover&&<div className="cover-preview"><img src={cover.url} alt={coverAlt||"Selected cover preview"}/><button type="button" className="remove-image" onClick={()=>setCover(null)} aria-label="Remove cover"><X size={16}/></button></div>}<label className="upload-drop">{busy==="cover"?<LoaderCircle className="spin"/>:<ImagePlus/>}<strong>{busy==="cover"?"Uploading…":"Choose cover image"}</strong><span>Natural aspect ratio · up to 4 MB</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>addCover(e.target.files?.[0])}/></label><label>Or use an image URL<input name="coverImage" value={cover?.url||""} onChange={e=>setCover(e.target.value?{url:e.target.value,name:"Remote image"}:null)} placeholder="https://…"/></label>{cover&&<label>Image description <span>For accessibility; never shown as a caption</span><input name="coverAlt" value={coverAlt} onChange={e=>setCoverAlt(e.target.value)} required placeholder="Describe what the image shows"/></label>}</fieldset>
    <div className="article-field"><div className="article-label"><strong>Article</strong><span>Paste formatted text or use the toolbar</span></div><div className="format-toolbar" aria-label="Formatting tools"><button type="button" onClick={()=>prefixLines("## ")}><Type size={15}/>Heading</button><button type="button" onClick={()=>replaceSelection("**","**")}><strong>B</strong>Bold</button><button type="button" onClick={()=>replaceSelection("*","*")}><Italic size={15}/>Italic</button><button type="button" onClick={()=>prefixLines("> ")}><Quote size={15}/>Quote</button><button type="button" onClick={()=>prefixLines("- ")}><List size={15}/>List</button><button type="button" onClick={()=>replaceSelection("[","](https://)")}><LinkIcon size={15}/>Link</button><button type="button" onClick={()=>setContent(cleanFormatting(content))}><Sparkles size={15}/>Clean up</button><button type="button" className={preview?"active":""} onClick={()=>setPreview(!preview)}><Eye size={15}/>{preview?"Edit":"Preview"}</button></div>{preview?<div className="editor-preview"><Markdown content={content}/></div>:<textarea ref={articleRef} className="content-input" name="content" required rows={22} value={content} onPaste={pasteRichText} onChange={e=>setContent(e.target.value)} placeholder="Paste an article here—headings, lists, bold text and links are preserved."/>}{preview&&<input type="hidden" name="content" value={content}/>}<p className="paste-hint"><ClipboardPaste size={14}/>Formatting pasted from web pages and documents is converted automatically.</p></div>
    <div className="editor-actions"><label className="inline-upload">{busy==="inline"?<LoaderCircle size={17} className="spin"/>:<ImagePlus size={17}/>} {busy==="inline"?"Uploading…":"Insert image at cursor"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>addInline(e.target.files?.[0])}/></label><button>{post?"Update post":"Save post"}</button></div></form>;
}
